# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [1]:
import numpy as np
zero = np.zeros(100)
print (zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


#### 2.Создать вектор размера 100, заполненный единицами

In [2]:
one = np.ones(100)
print (one)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


#### 3.Создать вектор размера 100, заполненный числом 3

In [3]:
three = np.full(100, 3)
print (three)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


#### 4. Как получить документацию о функции numpy.add из командной строки?

In [4]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

#### 5. Поменять 2 строки в матрице

In [5]:
a = np.random.random((3,3))
a[0,1]=a[1,0]
print(a)

[[0.13890333 0.97940395 0.39460032]
 [0.97940395 0.76620064 0.08553302]
 [0.7505414  0.85634577 0.70108625]]


#### 6. Создать вектор со значениями от 10 до 100

In [6]:
a = np.arange(10,101)
print(a)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


#### 7. Развернуть вектор (первый становится последним)

In [7]:
a = np.arange(10,101)
a = a[::-1]
print(a)

[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10]


#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [9]:
a = np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [10]:
a = np.arange(1, 6)
b = np.zeros(len(a)+3*(len(a)-1))
b[::3+1]=a
print(b)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 10. Создать 3x3 единичную матрицу

In [11]:
a = np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Создать массив 3x3x3 со случайными значениями

In [12]:
a = np.random.random((3,3))
print(a)

[[0.70843895 0.08018454 0.961487  ]
 [0.88302707 0.07685185 0.99707062]
 [0.50681195 0.15417553 0.10319076]]


#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [13]:
a = np.random.random((10,10))
minimum = a.min()
maximum = a.max()
print("min is ", minimum, " max is ", maximum)

min is  0.005815781440434931  max is  0.9892459350661681


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [14]:
a = np.random.random([30])
med = a.mean()
print(med)


0.4392867902317639


#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [15]:
a = np.ones([5, 5])
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [16]:
a = np.arange(25).reshape(5,5)
print(a)
b = np.fft.fft(a)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 10. +0.j          -2.5+3.4409548j   -2.5+0.81229924j  -2.5-0.81229924j
   -2.5-3.4409548j ]
 [ 35. +0.j          -2.5+3.4409548j   -2.5+0.81229924j  -2.5-0.81229924j
   -2.5-3.4409548j ]
 [ 60. +0.j          -2.5+3.4409548j   -2.5+0.81229924j  -2.5-0.81229924j
   -2.5-3.4409548j ]
 [ 85. +0.j          -2.5+3.4409548j   -2.5+0.81229924j  -2.5-0.81229924j
   -2.5-3.4409548j ]
 [110. +0.j          -2.5+3.4409548j   -2.5+0.81229924j  -2.5-0.81229924j
   -2.5-3.4409548j ]]


#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [17]:
a = np.diag([1,2,2,4], -1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 4 0]]


#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [18]:
a = np.zeros((8,8))
a[1::2,::2]=a[::2,1::2]=1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [19]:
a = np.unravel_index(100, (6,7,8))
print(a)

(1, 5, 4)


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [20]:
a = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Перемножить матрицы 5x3 и 3x2

In [22]:
a = np.ones((5,3))
b = np.ones((3,2))
print(np.dot(a,b))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [24]:
a = np.random.random(10)*10
a[(a>3)&(a<8)]*=-1
print(a)

[-7.11621389  8.08287422  0.49327978 -5.91833847 -3.33032928  8.03577239
 -4.17381092 -4.59694713 -7.99993876  2.59428556]


#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [25]:
a = np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 24. Есть генератор, сделать с его помощью массив

In [26]:
def generate():
    for i in range(10):
        yield i
a = np.fromiter(generate(), dtype=int, count = -1)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [27]:
a = np.linspace(0,1,12)[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 26. Отсортировать вектор

In [28]:
a = np.random.random(10)*10
a.sort()
print(a)

[0.40443992 1.37247233 2.88731326 3.47727099 3.63110767 3.81422849
 6.96771135 7.3339818  9.1570679  9.42864603]


#### 27. Проверить, одинаковы ли 2 numpy массива

In [29]:
a = np.random.random(10)*10
b = np.random.random(10)*10
c = np.allclose(a, b)
print(c)

False


#### 28. Сделать массив неизменяемым

In [30]:
a = np.random.random(10)
a.flags.writeable = False


#### 29. Найти n наибольших значений в массиве

In [31]:
a = np.random.random(10)*10
n = 2
print(a[np.argpartition(-a,n)[:n]])

[8.24925706 4.6749069 ]


#### 30. Заменить максимальный элемент на ноль

In [32]:
a = np.random.random(10)*10
a[a.argmax()]=0
print(a)

[3.34176445 2.61165989 4.88114133 6.88818464 1.37157324 0.95984551
 1.35294181 0.         4.71190438 7.46164062]


#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [33]:
a = np.zeros((10,10), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,10), np.linspace(0,1,10))
print(a)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [36]:
x = np.arange(10)
y = x + 0.5
c = 1.0 / np.subtract.outer(x,y)
print(c)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333 -0.11764706 -0.10526316]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615 -0.13333333 -0.11764706]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818 -0.15384615 -0.13333333]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222 -0.18181818 -0.15384615]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429 -0.22222222 -0.18181818]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4        -0.28571429 -0.22222222]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667 -0.4        -0.28571429]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.         -0.66666667 -0.4       ]
 [ 0.13333333  0.153846

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [37]:
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.uint8, np.uint16, np.uint32, np.uint64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

-128
127
-32768
32767
-2147483648
2147483647
-9223372036854775808
9223372036854775807
0
255
0
65535
0
4294967295
0
18446744073709551615
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 34. Напечатать все значения в массиве

In [38]:
np.set_printoptions(precision=3)
a = np.random.random((10,10))
print(a)

[[0.277 0.081 0.95  0.248 0.174 0.759 0.044 0.785 0.849 0.236]
 [0.021 0.216 0.041 0.706 0.86  0.576 0.102 0.925 0.295 0.484]
 [0.342 0.217 0.746 0.405 0.079 0.903 0.118 0.346 0.016 0.398]
 [0.994 0.428 0.87  0.217 0.475 0.766 0.672 0.214 0.351 0.768]
 [0.416 0.281 0.387 0.547 0.865 0.062 0.707 0.028 0.167 0.432]
 [0.337 0.448 0.86  0.551 0.147 0.418 0.451 0.224 0.195 0.524]
 [0.785 0.622 0.089 0.045 0.672 0.471 0.835 0.567 0.64  0.409]
 [0.522 0.85  0.786 0.745 0.282 0.717 0.868 0.145 0.656 0.339]
 [0.934 0.579 0.32  0.977 0.368 0.067 0.663 0.65  0.584 0.842]
 [0.922 0.33  0.77  0.119 0.175 0.49  0.609 0.673 0.314 0.993]]


#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [39]:
a = np.arange(10)
n = 5
index = (np.abs(a-n)).argmin()
print(a[index])

5


#### 36. Преобразовать массив из float в int

In [40]:
a = np.random.random(10)*10
a = a.astype(np.int32, copy=False)
print(a)

[5 4 0 0 0 5 9 7 4 6]


#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [41]:
a = np.arange(15)
for index, value in np.ndenumerate(a):
    print(index, value)

(0,) 0
(1,) 1
(2,) 2
(3,) 3
(4,) 4
(5,) 5
(6,) 6
(7,) 7
(8,) 8
(9,) 9
(10,) 10
(11,) 11
(12,) 12
(13,) 13
(14,) 14


#### 38. Случайно расположить p элементов в 2D массив

In [42]:
a = np.zeros((5,5))
p = 5
np.put(a, np.random.choice(range(n*n), p, replace=False), 5)
print(a)

[[0. 0. 0. 5. 5.]
 [0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [5. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0.]]


#### 39. Отнять среднее из каждой строки в матрице

In [43]:
a = np.arange(16).reshape(4,4)
b = a - a.mean(axis=1)
print(b)

[[ -1.5  -4.5  -7.5 -10.5]
 [  2.5  -0.5  -3.5  -6.5]
 [  6.5   3.5   0.5  -2.5]
 [ 10.5   7.5   4.5   1.5]]


#### 40. Отсортировать матрицу по n-ому столбцу

In [44]:
a = np.random.random((10, 10))*10
print(a)
n=0
print(a[a[:,n].argsort()])

[[1.233 7.427 4.656 3.89  1.268 0.284 6.312 3.817 4.081 5.055]
 [9.113 5.304 8.16  1.672 0.816 5.626 6.442 5.202 9.67  4.769]
 [3.887 1.578 9.63  2.737 1.564 7.528 5.981 2.413 2.365 5.046]
 [5.825 2.174 1.811 5.739 5.628 4.042 0.101 7.406 1.769 5.82 ]
 [1.626 5.348 8.472 1.994 5.054 3.459 7.183 2.748 9.877 6.518]
 [2.268 2.895 6.382 7.324 0.761 7.14  9.402 0.351 4.199 8.358]
 [9.228 4.06  5.959 6.897 4.05  8.886 2.976 6.113 4.943 8.528]
 [5.914 3.687 8.984 8.983 7.448 4.908 9.112 2.512 2.188 8.575]
 [4.185 3.372 1.086 5.913 8.381 5.951 5.357 2.629 2.665 2.69 ]
 [5.604 0.923 1.414 9.219 5.888 8.655 8.247 1.692 0.281 7.92 ]]
[[1.233 7.427 4.656 3.89  1.268 0.284 6.312 3.817 4.081 5.055]
 [1.626 5.348 8.472 1.994 5.054 3.459 7.183 2.748 9.877 6.518]
 [2.268 2.895 6.382 7.324 0.761 7.14  9.402 0.351 4.199 8.358]
 [3.887 1.578 9.63  2.737 1.564 7.528 5.981 2.413 2.365 5.046]
 [4.185 3.372 1.086 5.913 8.381 5.951 5.357 2.629 2.665 2.69 ]
 [5.604 0.923 1.414 9.219 5.888 8.655 8.247 1.692 0.28

#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [45]:
a = np.random.randint(0,10, (5,5))
print((~a.any(axis=0)).any())

False


#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [46]:
b = np.ones(4)
a = np.random.randint(0, len(b), 4)
print(a)
print(b)
b += np.bincount(a, minlength=len(b))
print(b)

[1 0 0 2]
[1. 1. 1. 1.]
[3. 2. 2. 1.]


#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [47]:
w,h = 16,16
a = np.random.randint(0, 2, (w,h,3)).astype(np.ubyte)
b = a[..., 0] * 256 * 256 + a[..., 1] * 256 + a[..., 2]
n = len(np.unique(b))
print (n)
print(np.unique(a))

4
[0 1]


#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [48]:
a = np.random.randint(0,10, (4,4,4,4))
sum = a.reshape(a.shape[:2] + (-1,)).sum(axis=-1)
print(sum)

[[77 56 67 83]
 [72 65 78 64]
 [70 97 72 83]
 [63 59 72 82]]
