In [1]:
import numpy as np

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$; $AB$ и $BA$ - неопределены (недопустимая операция)
   
   
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$; $AB$ - $2\times 3$; $BA$ - неопределена
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$; $AB$ - $8\times 8$;  $BA$ - $3\times 3$
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$. $AB$ - $4\times 4$; $BA$ - $4\times 4$

In [10]:
A = np.array([[1, 0], [2, 1], [10, 5], [5, 5]])
B = np.array([[1, 0], [2, 1], [10, 5], [5, 5]])
print('a)')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

a)


ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [11]:
A = np.array([[1, 0, 3, 4, 5], [1, 0, 3, 4, 5]])
B = np.array([[1, 0, 4], [2, 1, 5], [10, 5, 7], [5, 5, 8], [10, 5, 2]])
print('б)')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}') 

б)
Матрица AB
[[101  60  67]
 [101  60  67]]


ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

In [12]:
A = np.array([[1, 0, 4], [2, 1, 5], [10, 5, 7], [5, 5, 8], [10, 5, 2], [5, 2, 8], [1, 2, 9], [8, 9, 8]])
B = np.array([[1, 0, 3, 4, 5, 7, 5, 9], [1, 0, 3, 2, 5, 8, 2, 6], [1, 1, 3, 2, 5, 8, 2, 6]])
print('в)')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

в)
Матрица AB
[[  5   4  15  12  25  39  13  33]
 [  8   5  24  20  40  62  22  54]
 [ 22   7  66  64 110 166  74 162]
 [ 18   8  54  46  90 139  51 123]
 [ 17   2  51  54  85 126  64 132]
 [ 15   8  45  40  75 115  45 105]
 [ 12   9  36  26  60  95  27  75]
 [ 25   8  75  66 125 192  74 174]]
Матрица BA
[[213 165 240]
 [181 124 181]
 [183 125 186]]


In [13]:
A = np.array([[1, 0, 5, 7], [2, 1, 6, 7], [10, 5, 8, 4], [5, 5, 4, 1]])
B = np.array([[1, 0, 6, 7], [2, 1, 7, 3], [10, 5, 3, 6], [5, 5, 7, 2]])
print('г)')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

г)
Матрица AB
[[ 86  60  70  51]
 [ 99  66  86  67]
 [120  65 147 141]
 [ 60  30  84  76]]
Матрица BA
[[ 96  65  81  38]
 [ 89  51  84  52]
 [ 80  50 128 123]
 [ 95  50 119 100]]


__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$ 

In [14]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Сумма матриц A + B\n{A + B}')
print(f'Произведение AB\n{np.dot(A, B)}')

Сумма матриц A + B
[[ 5 -3]
 [ 3  5]]
Произведение AB
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [30]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2 ,-1]])
C = np.array([[2 ,-4],[1, 1]])

B2 = -2*B

print(f"Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 = \n{3*A + B2 + 4*C}\n") 

Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 = 
[[ 11  -5]
 [  9 -12]]



__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [31]:
A = np.array([[4, 1], [5, -2], [2, 3]])
AT = A.T
print(f'Матрица AA^T\n{np.dot(A, AT)}')
print(f'Матрица A^T*A\n{np.dot(AT, A)}')

Матрица AA^T
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица A^T*A
[[45  0]
 [ 0 14]]


__5.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

  б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [34]:
A = np.array([[4, 1], [5, -2]])
print('а)')
print(f'Определитель:\n sin^2(x)+cos^2(x) = 1')

а)
Определитель:
 sin^2(x)+cos^2(x) = 1


In [35]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print('б)')
print(f'Определитель:\n 4 * 5 * 9 = 180')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

б)
Определитель:
 4 * 5 * 9 = 180
Определитель:
180


In [37]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('в)')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

в)
Определитель:
-0


__6.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [39]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Определитель:\n{np.linalg.det(A):.0f}')
print('Так как определитель ноль -> матрица вырожденная')

Определитель:
0
Так как определитель ноль -> матрица вырожденная


__7.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

In [40]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Ранг матрицы: {np.linalg.matrix_rank(A)}')

Ранг матрицы: 2
